name: Manual Release Creator

on:
  workflow_dispatch:
    inputs:
      from_tag:
        description: 'Previous tag (e.g. v1.0.0)'
        required: true
        type: string
      to_tag:
        description: 'New tag (e.g. v1.1.0)'
        required: true
        type: string
      release_title:
        description: 'Release title (optional)'
        required: false
        type: string

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release notes
        id: notes
        run: |
          NOTES=$(gh api repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name=${{ inputs.to_tag }} \
            -f previous_tag_name=${{ inputs.from_tag }} \
            -q .body)
          echo "$NOTES" > release_notes.txt
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub release
        run: |
          gh release create "${{ inputs.to_tag }}" \
            --title "${{ inputs.release_title || format('Release {0}', inputs.to_tag) }}" \
            --notes-file release_notes.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
